stages:
  - lint
  - build
  - test
  - release


lint:
  stage: lint
  image: golangci/golangci-lint:latest
  script:
    - golangci-lint run


build:
  stage: build
  image: golang:latest
  script:
    - go build -o BanForge


test:
  stage: test
  image: golang:latest
  script:
    - go test
 
