stages:
  - lint
  - build
  - test
  - release


lint:
  stage: lint
  image: golangci/golangci-lint:latest
  script:
    - golangci-lint run


build:
  stage: build
  image: golang:latest
  script:
    - go mod download
    - go build -o banforge ./cmd/banforge/main.go 


test:
  stage: test
  image: golang:latest
  script:
    - go test ./...
 
